name: Check Event Type

on:
  repository_dispatch:
    types:
      - xpto
  workflow_dispatch:
  push:
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      #- name: Print Event Name
      #  run: echo "Event name: ${{ github.event_name }}"

      - name: Print Full Event Data
        run: echo '${{ toJson(github.event) }}'
